@extends('layouts.app')

@section('content')
    <div class="container">
        {{--            Game board--}}
        <div class="row">
            {{--            Rules--}}
            <div class="col-lg-3">
                <div class="card h-100 text-center" id="ruleCard">
                    <div class="card-header">{{ __('RULES') }}</div>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ __('Classic Sudoku') }}</li>
                    </ul>
                </div>
            </div>

            {{--            Grid--}}
            <div class="col-lg-6">
                <div class="card h-100 text-center" id="gridCard">
                    <div class="card-header align-items-end">
                        <p> {{ strtoupper($grid->title) }} by {{ $grid->user->name }}</p>
                    </div>

                    <div class="card-body">
                        <p id="coordinates">r0c0 / row: 0 column: 0 box: 0</p>
                        <div id="grid" data-mode="solving">
                            {{--                            Grid generated by grid-generation.js--}}
                            <script onload="generate3x3({{ $contents }})" src="{{ asset('js/grid-generation.js') }}" defer></script>
                        </div>
                        <div id="testArea">REPLACE THIS</div>
                    </div>
                </div>
            </div>

            {{--            Controls--}}
            <div class="col-lg-3">
                <div class="card text-center" id="controlCard">
                    <div class="card-header">{{ __('CONTROLS') }}</div>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div class="row justify-content-center">
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('1')" type="button">1</button>
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('2')" type="button">2</button>
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('3')" type="button">3</button>
                            </div>
                            <div class="row justify-content-center">
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('4')" type="button">4</button>
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('5')" type="button">5</button>
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('6')" type="button">6</button>
                            </div>
                            <div class="row justify-content-center">
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('7')" type="button">7</button>
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('8')" type="button">8</button>
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('9')" type="button">9</button>
                            </div>
                            <div class="row justify-content-center">
                                <button class="btn btn-outline-info m-1" onclick="inputHandler('0')" type="button">0</button>
                                <button class="btn btn-outline-info m-1" id="backspaceBtn" onclick="inputHandler('Backspace')" type="button"></button>
                            </div>
                        </li>

                        <li class="list-group-item btn-group">
                            <button class="btn btn-outline-dark" id="penBtn" aria-pressed="true" type="button" onclick="modeSwitch('pen')"></button>
                            <button class="btn btn-outline-info" id="pencilBtn" aria-pressed="false" type="button" onclick="modeSwitch('pencil')"></button>
                        </li>

                        <li class="list-group-item btn-group">
                            <button class="btn btn-outline-primary" id="finishBtn" type="button" onclick="validatePostFinish()"></button>
                            <button class="btn btn-outline-danger" id="restart" type="button"></button>
                        </li>
                    </ul>
                </div>
            </div>

            {{--            Modal alert for feedback when finishing puzzle correctly--}}
            <div class="modal" id="successModal" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">{{ __('Congratulations!') }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p> {{ __('Puzzle completed!') }}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

            {{--            Modal alert for feedback when finishing puzzle incorrectly--}}
            <div class="modal" id="failureModal" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">{{ __('Uh, Oh!') }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p> {{ __('Mistakes have been found!') }}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {{--            Comments and ratings--}}
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header" id="commentCard">{{ __('COMMENTS') }}</div>

                    <div class="card-body">
                        <div class="bg-danger">Space for comment module</div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">{{ __('RATINGS') }}</div>

                    <div class="card-body">
                        <div class="bg-danger">Space for rating module</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
